CREATE TABLE restaurant(
                           id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           city varchar(100) NOT NULL,
                           name varchar(100) NOT NULL,
                           estimated_cost int NOT NULL,
                           average_rating varchar(10) NOT NULL,
                           votes int NOT NULL
);

INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('Miami', 'Byg Company', 1600, '4.9', 16203);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('Miami', 'Cherry', 200, '4.2', 1);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('City2', 'Rest2.1', 400, '4.4', 22);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('City2', 'Rest2.2', 100, '4.6', 333);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('City3', 'Rest3.1', 50, '4.8', 4444);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('City3', 'Rest3.2', 80, '4.0', 55555);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('City3', 'Rest3.3', 85, '4.2', 666666);
INSERT INTO restaurant (city, name, estimated_cost, average_rating, votes) VALUES ('Minsk', 'Vasilki', 20, '4.0', 81);

drop table restaurant;